### ISSUE TITLE
Cannot compile on kubuntu 19.10

### ISSUE THREAD

**Issue by fluca1978** [dragotin/pdfquirk#7]
I'm probably setting something wrong in my environment, but when I try to compile I get an error:

```
% cmake src && make
CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.13)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
CMake Warning (dev) at CMakeLists.txt:2 (add_executable):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "pdfquirk" links to target "Qt5::Widgets" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /home/luca/Downloads/pdfquirk-0.91
[ 16%] Building CXX object CMakeFiles/pdfquirk.dir/main.o
In file included from /home/luca/Downloads/pdfquirk-0.91/src/main.cpp:18:
/home/luca/Downloads/pdfquirk-0.91/src/dialog.h:21:10: fatal error: QDialog: No such file or directory
   21 | #include <QDialog>
      |          ^~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/pdfquirk.dir/build.make:63: CMakeFiles/pdfquirk.dir/main.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/pdfquirk.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

```

My system is:

```
% lsb_release -a && apt-file show qtbase5-dev | grep QDialog
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 19.10
Release:        19.10
Codename:       eoan
qtbase5-dev: /usr/include/x86_64-linux-gnu/qt5/QtWidgets/QDialog
qtbase5-dev: /usr/include/x86_64-linux-gnu/qt5/QtWidgets/QDialogButtonBox
```

**Comment by dragotin** [comment]
I think your problem is that you call `cmake src` rather than calling it in the top dir.

Please try from the pdfquirk "top"-directory:
```
mkdir build
cd build
cmake ..
make 
```

**Comment by dragotin** [comment]
Improved the "Build from Source" paragraph on the website https://dragotin.github.io/quirksite/

**Comment by fluca1978** [comment]
Sorry, but something is still not working:


```
% pwd
/home/luca/Downloads/pdfquirk-0.91/build

% cmake -DCMAKE_INSTALL_PREFIX=/usr/local ..
CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.13)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
CMake Warning (dev) at CMakeLists.txt:2 (add_executable):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "pdfquirk" links to target "Qt5::Widgets" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /home/luca/Downloads/pdfquirk-0.91

```

Now the last line states the build files have been placed one folder up with regard to the `build` directry I'm in, that is effectively empty. This means `make` cannot be run.
Am I missing something?

**Comment by dschmidt** [comment]
Can you try with a fresh checkout? 

To me it looks like you have some old CMake cache files etc lying in either your build or in the source folder from your previous experiments with `cmake src`.

```
git clone https://github.com/dragotin/pdfquirk.git
mkdir pdfquirk/build
cd pdfquirk/build
cmake -DCMAKE_INSTALL_PREFIX=/usr/local ..
cmake --build .
```

Should work or give you more reasonable error messages.

**Comment by fluca1978** [comment]
Yes, I do confirm that with a fresh clone it worked.
Thanks
